<a href="https://colab.research.google.com/github/67015063/lab03/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015063 ชื่อ :ธัญญเรศ ศรีวิชัย

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [ ]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
def is_leap(year) :
  if year % 4 == 0 :
    if year % 100 == 0 :
      if year % 400 == 0 :
        return True
      else :
        return False
    else :
      return True
  else :
    return False

def day_of_year(day, month, year) :
  if is_leap(year) :
    days_in_month[1] = 29
  else :
    days_in_month[1] = 28
  day_of_years = sum(days_in_month[:month - 1]) + day
  return day_of_years
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365


Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [34]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
def is_leap(year) :
  if year % 4 == 0 :
    if year % 100 == 0 :
      if year % 400 == 0 :
        return True
      else :
        return False
    else :
      return True
  else :
    return False

def day_of_year(day, month, year) :
  if is_leap(year):
    days_in_month[1] = 29
  else :
    days_in_month[1] = 28
  day_of_years = sum(days_in_month[:month - 1]) + day
  return day_of_years

def day_in_year(year) :
  return 366 if is_leap(year) else 365

def date_diff(date1, date2):
  splited_date1 = date1.split("-")
  year1 = int(splited_date1[2])
  month1 = int(splited_date1[1])
  day1 = int(splited_date1[0])

  splited_date2 = date2.split("-")
  year2 = int(splited_date2[2])
  month2 = int(splited_date2[1])
  day2 = int(splited_date2[0])

  years = []
  for year in range(year1 + 1, year2):
    years.append(year)

  total_date_by_year = []
  for year in years:
    total_date_by_year.append(day_in_year(year))

  if year2 - year1 > 0:
    rank_of_endyear1 = day_of_year(day=31, month=12, year=year1)
    rank_of_date1 = day_of_year(day=day1, month=month1, year=year1)
    total_date_by_year.append(rank_of_endyear1 - rank_of_date1 + 1)
    rank_of_date2 = day_of_year(day=day2, month=month2, year=year2)
    total_date_by_year.append(rank_of_date2)
  else:
    rank_of_date1 = day_of_year(day=day1, month=month1, year=year1)
    rank_of_date2 = day_of_year(day=day2, month=month2, year=year2)
    total_date_by_year.append(rank_of_date2 - rank_of_date1 + 1)
  all = sum(total_date_by_year)
  return all

print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001")) # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)



731
76
367
366
366
365


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [37]:
def is_leap(year):
  if year % 4 == 0:
    if year % 100 == 0:
      if year % 400 == 0:
        return True
      else:
        return False
    else:
      return True
  else:
    return False

def day_in_year(year):
  if is_leap(year):
    return 366
  else:
    return 365

def days_in_month(month, year):
  days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
  if is_leap(year):
    days[1] = 29
  return days[month - 1]

def day_of_year(day, month, year):
  if month < 1 or month > 12:
    return -1
  if day < 1 or day > days_in_month(month, year):
    return -1
  day_of_year = sum(days_in_month(m, year) for m in range(1, month)) + day
  return day_of_year

def date_diff(date1, date2):
  a = date1.split("-")
  b = date2.split("-")

  if len(a) != 3 or len(b) != 3:
    return -1

  d1, m1, y1 = map(int, a)
  d2, m2, y2 = map(int, b)

  if day_of_year(d1, m1, y1) == -1 or day_of_year(d2, m2, y2) == -1:
    return -1

  if (y1 > y2) or (y1 == y2 and day_of_year(d1, m1, y1) > day_of_year(d2, m2, y2)):
    date1, date2 = date2, date1
    d1, m1, y1 = d2, m2, y2
    d2, m2, y2 = map(int, a)

  years = list(range(y1 + 1, y2))
  total_date_by_year = [day_in_year(year) for year in years]

  if y2 - y1 > 0:
    rank_of_endyear1 = day_of_year(31, 12, y1)
    rank_of_date1 = day_of_year(d1, m1, y1)
    total_date_by_year.append(rank_of_endyear1 - rank_of_date1 + 1)
    rank_of_date2 = day_of_year(d2, m2, y2)
    total_date_by_year.append(rank_of_date2)
  else:
    rank_of_date1 = day_of_year(d1, m1, y1)
    rank_of_date2 = day_of_year(d2, m2, y2)
    total_date_by_year.append(rank_of_date2 - rank_of_date1 + 1)
  return sum(total_date_by_year)
# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

731
76
367
366
366
365
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [52]:
import math
def simulate_fish_population(n, p):
  l_egg = []
  l_baby = [0]
  l_adult = [n]
  k=0

  for i in range(120):
    if i == 0:
      l_egg.append((sum(l_adult)/2)*300)
      print(i+1,"Egg:",int(l_egg[i]),"Baby:",int(l_baby[i]),"Adult:",sum(l_adult),"Fish:",n)
    elif i > 0:
      l_baby.append(l_egg[i-1]*(100-p)/100)
      l_egg.append((sum(l_adult)/2)*300)
      l_adult.append(l_baby[i-1]*(100-p)/100)
    print(i+1,"Egg:",int(l_egg[i]),"Baby:",int(l_baby[i]),"Adult:",sum(l_adult),"Fish:",sum(l_adult)+int(l_baby[i]))

    for j in range(len(l_adult)):
      l_adult[j] = round((l_adult[j]*(100-p)/100))
    if i % 59 == 0 and i > 0:
      l_adult[k] =0
simulate_fish_population(n, p)

# Run simulation
n = 2   #Initial number of fish
p = 10   #Monthly mortality rate

# simulate_fish_population(n, p)

# ถ้าเริ่มต้นด้วยปลา 2 ตัว ตายเดือนละ 10%
# เดือนที่ 1 ไข่ 300 ไบ
# เดือนที่ 2 ไข่ 300 ใบ + ลูกปลา 270 ตัว
# เดือนที่ 3 ไข่ 300 ใบ + ลูกปลา 270 ตัว + ปลาโตเต็มวัย 243 ตัว + 2 = 515 ตัว
#เดือน 4 ออกไข่300 + ลูก270 +  243/2=120 *300


1 Egg: 450 Baby: 0 Adult: 3 Fish: 3
1 Egg: 450 Baby: 0 Adult: 3 Fish: 3
2 Egg: 450 Baby: 427 Adult: 3.0 Fish: 430.0
3 Egg: 450 Baby: 427 Adult: 409.125 Fish: 836.125
4 Egg: 58350 Baby: 427 Adult: 795.125 Fish: 1222.125
5 Egg: 113400 Baby: 55432 Adult: 1162.125 Fish: 56594.125
6 Egg: 165750 Baby: 107730 Adult: 53765.875 Fish: 161495.875
7 Egg: 7661850 Baby: 157462 Adult: 153422.5 Fish: 310884.5
8 Egg: 21862800 Baby: 7278757 Adult: 295341.375 Fish: 7574098.375
9 Egg: 42086250 Baby: 20769660 Adult: 7195394.625 Fish: 27965054.625
10 Egg: 1025343600 Baby: 39981937 Adult: 26566801.0 Fish: 66548738.0
11 Egg: 3785769150 Baby: 974076420 Adult: 63221301.625 Fish: 1037297721.625
12 Egg: 9009035550 Baby: 3596480692 Adult: 985432836.0 Fish: 4581913528.0
13 Egg: 140424178950 Baby: 8558583772 Adult: 4352817850.875 Fish: 12911401622.875
14 Egg: 620276543700 Baby: 133402970002 Adult: 12265831541.875 Fish: 145668801543.875
15 Egg: 1747880994600 Baby: 589262716515 Adult: 138385361466.375 Fish: 7276480779

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [12]:
str1 = input("")
str2 = input("")
def find_mismatch(str1, str2) :
  str1 = str1.lower()
  str2 = str2.lower()
  if str1 == str2 :
    return 0

  def edit(str1,str2) :
    lenth1,lenth2 = len(str1),len(str2)
    if abs(lenth1 - lenth2) > 1 :
      return False
    i=0
    j=0
    diff = False
    while i <lenth1 and j<lenth2 :
      if str1[i] != str2[j] :
        if diff :
          return False
        diff = True
        if lenth1 > lenth2 :
          i+=1
        elif lenth1 < lenth2 :
          j+=1
        else :
          i+=1
          j+=1
      else :
        i+=1
        j+=1
    return True

  if edit(str1,str2) :
    return 1
  return 2
print(find_mismatch(str1, str2))

book
bool
1


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [48]:

def find_mismatch(str1, str2) :
  str1 = str1.lower()
  str2 = str2.lower()
  if str1 == str2 :
    return 0

  def edit(str1,str2) :
    lenth1,lenth2 = len(str1),len(str2)
    if abs(lenth1 - lenth2) > 1 :
      return False
    i=0
    j=0
    diff = False
    while i <lenth1 and j<lenth2 :
      if str1[i] != str2[j] :
        if diff :
          return False
        diff = True
        if lenth1 > lenth2 :
          i+=1
        elif lenth1 < lenth2 :
          j+=1
        else :
          i+=1
          j+=1
      else :
        i+=1
        j+=1
    return True

  if edit(str1,str2) :
    return 1
  return 2

def spelling_correction(input_string: str, correct_spells: list[str]) -> str:
  lower_input_string: str = input_string.lower()
  lower_input_words: list[str] = lower_input_string.split(" ")

  lower_correct_spells: list[str] = [word.lower() for word in correct_spells]

  output_string: str = ""
  for input_word in lower_input_words:
    if len(input_word) > 2:
      compare_time: int = 0
      for output_word in lower_correct_spells:
        is_matched: int = find_mismatch(str1=input_word, str2=output_word)
        compare_time += 1

        if is_matched == 0:
          output_string += f"{input_word} "
          break
        elif is_matched == 1:
          output_string += f"{output_word} "
          break

        if compare_time == len(lower_correct_spells):
          output_string += f"{input_word} "
    else:
      output_string += f"{input_word} "
  return output_string

sentence: str = "Thes is the Firs cas"
correct_spells: list[str] = ["that", "first", "case", "car"]
spelled_sentence: str = spelling_correction(input_string=sentence, correct_spells=correct_spells)
print(spelled_sentence)

thes is the first case 


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [ ]:
def find_word_horizontal(crosswords, word):
  for rowin , row in enumerate(crosswords) :
    rowstr = "".join(row)
    col = rowstr.find(word)
    if col != -1 :
      return (rowin ,col)
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
word='cat'
re = find_word_horizontal(crosswords,word)
print(re)

(2, 1)


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [ ]:
def find_word_vertical(crosswords, word):
  numrow = len(crosswords)
  if numrow > 0 :
    numcol = len(crosswords[0])
  else :
    numcol = 0

  for colin in range(numcol) :
    colstr = "".join(crosswords[rowin][colin]for rowin in range(numrow))
    rowin = colstr.find(word)
    if rowin != -1 :
      return(rowin,colin)
  return None
crosswords=[
    ['s','d','o','g'],
    ['c','u','c','m'],
    ['a','c','a','t'],
    ['t',' e','t','k']]
word='cat'
re = find_word_vertical(crosswords,word)
print(re)

(1, 0)


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [42]:
def word_horizontal(crosswords, word) :
  for rowin, row in enumerate(crosswords) :
    row_str = "".join(row)
    colin = row_str.find(word)
    if colin != -1 :
      return (rowin, colin)
    return None

def word_vertical(crosswords, word) :
  num_rows = len(crosswords)
  num_cols = len(crosswords[0]) if num_rows > 0 else 0

  for colin in range(num_cols):
    col_str = "".join(crosswords[rowin][colin] for rowin in range(num_rows))
    rowin = col_str.find(word)
    if rowin != -1 :
      return (rowin, colin)
  return None

def capitalize_word_in_crossword(crosswords, word) :
  cw = [row[:] for row in crosswords]
  post = find_word_horizontal(crosswords, word)
  if post :
    rowin, colin = post
    for i in range(len(word)) :
      crosswords[rowin][colin + i] = crosswords[rowin][colin + i].upper()

  vertical_position = find_word_vertical(crosswords, word)
  if vertical_position:
    rowin, colin = vertical_position
    for i in range(len(word)) :
      crosswords[rowin + i][colin] = crosswords[rowin + i][colin].upper()

    if crosswords == cw :
        return cw
    return crosswords

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'x', 'a', 't'],
    ['t', 'e', 't', 'k']]
word = 'cat'

re = capitalize_word_in_crossword(crosswords, word)
for row in re :
  print(row)


['s', 'd', 'o', 'g']
['C', 'u', 'c', 'm']
['A', 'x', 'a', 't']
['T', 'e', 't', 'k']
